const BlogPosts = {
  1: {
    id: 1,
    title: 'Making regulation more accessible: Value driven by the ORP',
    author: 'Better Regulation Executive',
    date: '8 March 2023',
    tags: [{ name: 'Content tag', href: '#' }],
    description:
      'The Open Regulation Platform (ORP) has a simple objective: to create a platform which provides UK regulation as enriched, machine-readable data. By meeting this objective, the ORP will be an enabling service that can support the development of a range of tools that ensure regulation in the UK is digital-first and accessible to business in smarter ways.',
    // youtubeId: 'X2juNBpHtaU',
    image: {
      name: 'laptop.jpg',
      alt: '',
    },
    content:
      '<p>The Open Regulation Platform (ORP) has a simple objective: to create a platform which provides UK regulation as enriched, machine-readable data. By meeting this objective, the ORP will be an enabling service that can support the development of a range of tools that ensure regulation in the UK is digital-first and accessible to business in smarter ways.</p>' +
      '<p><a href="https://www.gov.uk/government/publications/build-back-better-our-plan-for-growth/build-back-better-our-plan-for-growth-html" target="_blank" rel="noopener noreferrer">Less than a third</a> of UK businesses believe that the UK Government’s approach to regulation supports them in bringing new products and services to market. For the UK to have a regulatory system that is pro-innovation and provides a supportive environment to dynamic entrepreneurial business across all industries, regulatory reform needs to encourage new processes, products and business models.</p>' +
      '<p>The Open Regulation Platform helps to achieve several goals in the Innovation pillar from the Treasury’s Build Back Better: Plan for Growth report and the project is directly highlighted in the section on developing a regulatory system for an innovative economy. The strategy commits to “[harnessing] technology to ease the burdens of engaging with regulation” by “[converting] UK business legislation into machine-readable data to drive the development of RegTech apps.”</p>' +
      '<p>The ORP will ensure that there is co-ordinated digitisation and standardisation of information produced by regulators. This is something that will only become more important over time as new or adapted regulations are added to a growing corpus. The ORP will support efforts made by the UK Government and regulators – individually and collectively – to progress work that makes regulation easier to understand and access. </p>' +
      '<p>The need for accessible and easily understood regulation has been highlighted in the last few years. The response to the COVID-19 pandemic demonstrated how quickly regulations can change or be introduced. The UK’s departure from the European Union has also required an ongoing response from regulators which impacts UK businesses. <a href="https://www.gov.uk/government/news/the-retained-eu-law-revocation-and-reform-bill-2022#:~:text=Retained%20EU%20Law%20is%20a,on%20the%20statute%20book%20indefinitely." target="_blank" rel="noopener noreferrer">The Retained EU Law Bill</a> that is currently progressing through Parliament seeks to enable retained EU rules to be modified, updated or removed so that they are well-suited for the UK. As UK regulation changes due to the powers proposed in the Bill the demand for regulatory guidance and information that is easy to find and understand is likely to be enhanced. </p>' +
      '<p>In addition to Government or regulator led projects that seek to improve the accessibility of regulatory guidance, the ORP also supports private sector innovators and entrepreneurs. Tools – known as Reg Tech – that help businesses to understand their regulatory obligations across the broad range of regulations that they often need to comply with. They can also be part of the process that allows businesses to demonstrate their compliance. Reg Tech providers can leverage the ORP as part of their product development.</p>' +
      '<p>Currently, <a href="https://app.dev.cannonband.com/about#:~:text=BEIS%E2%80%99s%20Business%20Perception%20Survey%20from%202020" target="_blank" rel="noopener noreferrer">around eight staff days</a> per month are spent on average by UK business complying with regulation. Reg Tech tools can support greater efficiency in achieving regulatory compliance, freeing time and resource for business to allocate to revenue-generating or cost-saving activities.  </p>' +
      '<p>As well as supporting businesses grow by reducing their regulatory burden, dynamic and competitive Reg Tech markets can contribute to the UK economy on their own accord. In the finance industry the Financial Conduct Authority has embraced the approach the ORP now seeks to take by making their guidance and other regulatory material digitally accessible and standardised through their digital handbook. The <a href="https://www.gov.uk/government/publications/the-kalifa-review-of-uk-fintech" target="_blank" rel="noopener noreferrer">Kalifa Report</a>, which reviewed Reg Tech tools in the financial industry (Fin Tech), highlighted the importance of the FCA’s overall approach in supporting the UK’s Fin Tech sector which generated £11bn of revenue in 2021.  </p>' +
      '<p>The ORP has been designed to help current or future Reg Tech providers across a broad range of industries to access the dataset of regulatory material they can build from. The platform has a series of API endpoints that can be used alongside a web portal that can be used for online searching of regulatory material to access regulatory material easily and automatically.</p>' +
      '<p>The Better Regulation Executive within the Department for Business and Trade is uniquely placed to co-ordinate this work. The BRE’s existing relationships with regulators across the public sector and knowledge of the Reg Tech sector has ensured that development of the ORP has placed the needs and experiences of regulators and Reg Tech providers at the centre of the project. Our next blog post will reflect on the design and development approach we have employed, and will share the key user research insights.</p>' +
      '<p>We will continue to take a user-centred approach to developing the ORP, through user testing and frequent engagement with regulators and Reg Tech creators. We will also coordinate with other efforts to organise regulation standards such as the <a href="https://www.gov.uk/government/publications/better-regulation-framework" target="_blank" rel="noopener noreferrer">Better Regulation Framework</a>. Over the coming months and years, the ORP will support the Government, regulators and Reg Tech providers to transform how UK businesses find, understand and comply with regulatory guidance and legislation. </p>',
  },
  2: {
    id: 2,
    title: 'Strategy and product development',
    author: 'Better Regulation Executive',
    date: '26 May 2023',
    tags: [{ name: 'Content tag', href: '#' }],
    description:
      'The Open Regulation Platform (ORP) is a digital product which seeks to provide a collated repository of UK regulation. The user interface will publish an enriched machine-readable dataset that can be used by businesses, government, regulators and third parties to develop products to reduce the cost of compliance with regulation in smarter, less burdensome ways.',
    image: {
      name: 'lightbulbs.jpg',
      alt: '',
    },
    content:
      '<p>The Open Regulation Platform (ORP) is a digital product which seeks to provide a collated repository of UK regulation. The user interface will publish an enriched machine-readable dataset that can be used by businesses, government, regulators and third parties to develop products to reduce the cost of compliance with regulation in smarter, less burdensome ways. End users can use the service to research UK regulation in one convenient central repository. </p>' +
      '<p>Through providing this open access and informative data, the ORP hopes to catalyse innovation by spurring the development of new regulatory tools using ORP data. </p>' +
      '<h3 class="govuk-heading-m">The ORP’s Vision</h3>' +
      '<p>We believe better regulation data is an enabler that will unlock benefits for businesses that will support longer-term economic growth through reducing compliance costs, making it easier for foreign businesses to operate in the UK and to stimulate the emerging RegTech market. </p>' +
      "<p>The ORP's vision comprises three critical components: </p>" +
      '<h4 class="govuk-heading-s">1 - Increased compliance & smarter regulation:  </h4>' +
      '<p>The first component of the ORP’s vision is to increase compliance through smarter regulation. Regulation data is currently dispersed and published at different levels of machine readability. With an enriched and dynamic dataset of regulators, business can easily understand and adhere to regulatory requirements, while regulators can access all regulations in one place. This integration of regulatory data will simplify the process for legal, policy, and other teams to find the information they need for their work, reducing non-compliance.  </p>' +
      '<h4 class="govuk-heading-s">2 - A single point of entry increasing regulatory efficiency:</h4>' +
      '<p>The second component of the ORP’s vision is to provide a single point of entry to increase regulatory efficiency. By creating a single entry-point for regulatory material, including guidance and market data, the ORP will promote an open, transparent, and symbiotic relationship between Government, regulators, RegTech and businesses.  </p>' +
      '<p>Our vision is to work with regulators in making regulation more machine readable (through metadata and mark up standards) and more connected (through ORP). The platform will simplify the process of managing regulatory requirements and in turn promote regulatory efficiency.  </p>' +
      '<h4 class="govuk-heading-s">3 - Stimulate nascent industries using accessible and structured datasets:</h4>' +
      '<p>The third and final component of the ORP’s vision is to stimulate nascent industries using accessible and structured datasets. The platform will enable a new market in third-party applications and tools. Access to this data will unlock innovation from third-party software services and new in-house solutions. The benefits of this will be reduced costs of compliance and enabling the development of new RegTech tools.</p>' +
      '<h3 class="govuk-heading-m">The ORP Strategy</h3>' +
      '<p>To achieve the vision outlined above, we are focussing on driving user adoption through a robust data supply strategy. The data we are focussing on is the regulatory material that is drafted and published by UK regulators. </p>' +
      '<p>To have a significant impact, the ORP vision implies that the platform must hold all up-to-date regulatory data and ensure that it is enriched to allow users to build tools and improve regulatory compliance. To secure a critical supply of data, we will increase user adoption, particularly by regulators who are the data owners, to achieve a high level of data enrichment. </p>' +
      '<p>Adoption by regulators will allow the ORP to achieve a data supply and a critical mass of data that will unlock the benefits outlined in the vision statements. Therefore, we have developed the product to align with three key factors that drive user adoption. Firstly, we will focus on marketing and advertising the benefits of the product, identifying early adopters of the product and engaging with wider user networks. Secondly, we will increase the ORP’s value proposition by improving the product through product iteration, making it increasingly useful to early adopters and attracting new users. Finally, we will embed the product in publishing processes and standards, closely linking it to ongoing digital strategies, needs, and priorities across regulatory entities and HMG.</p>' +
      '<p>By focussing on these drivers in unison, the ORP will promote adoption amongst regulators and create a valuable product, unlocking the benefits outlined in the vision and business case.</p>' +
      '<h3 class="govuk-heading-m">Development of the ORP </h3>' +
      '<p>In the current stage of product development, we have achieved significant progress towards these goals:</p>' +
      '<ol class="govuk-list govuk-list--number">' +
      '<li>We have identified regulators that could become early adopters of the product and started exploratory conversations with them.</li>' +
      '<li>We have developed and tested the initial iteration of the ORP platform, making improvements and enhancements based on user feedback such as improving the end of the upload journey, setting filters by frequency of use, and refining data enrichment features. </li>' +
      '<li>We have identified integration opportunities with government entities to promote adoption amongst regulators.</li>' +
      '</ol>',
  },
  3: {
    id: 3,
    title:
      'Enhancing Regulatory Innovation: Reflections from a discussion with innovators ',
    author: 'Better Regulation Executive',
    date: '09 Jun 2023',
    tags: [{ name: 'Content tag', href: '#' }],
    description:
      'In April, the Better Regulation Executive (BRE) organised an event that brought together regulators, Reg Tech providers, and academics. The discussion centred on regulatory innovation.  We demonstrated the Open Regulation Platform (see video, right) and were joined by individuals at the forefront of making the regulatory landscape smarter and more dynamic.',
    youtubeId: 'DedKWKc_B_Y',
    content:
      '<p>In April, the Better Regulation Executive (BRE) organised an event that brought together regulators, Reg Tech providers, and academics. The discussion centred on regulatory innovation.  We demonstrated the Open Regulation Platform (see video, right) and were joined by individuals at the forefront of making the regulatory landscape smarter and more dynamic. This blog reflects on some of the key points that were raised during the event and discusses how the ORP may be able to support the ambitions of regulators to reduce the costs of compliance. </p>' +
      '<h3 class="govuk-heading-m">The importance of metadata standards</h3>' +
      '<p>As we have highlighted in other posts, one of the key ways the ORP can add value to users is by enriching documents with consistent metadata. This will provide the structure to the data that will help both machines and people to sort and filter it. To do this effectively (and in a way that will support the dozens of regulators in the UK that cover the breadth of the UK economy) it is vital for documents to be classified in a consistent manner – a metadata standard. The value of a standard, though, goes far beyond facilitating the ORP. It would support the wider goals of the regulatory community in a variety of ways.</p>' +
      '<p>For regulators, the enhancement of their own individual websites and digital projects may also rely on data consistency. The need for standardisation is only achieved when multiple regulators collaborate, which is something that is happening more often. Whether it be the <a href="https://www.drcf.org.uk/" target="_blank" rel="noopener noreferrer">Digital Regulation Co-operation Forum</a> striving for coherence between four digital regulators, the three regulators involved in protecting the UK’s water supply through <a href="https://www.ofwat.gov.uk/regulated-companies/rapid/" target="_blank" rel="noopener noreferrer">RAPID</a> or a new project for bodies that hold UK financial reporting information including a new <a href="https://www.gov.uk/government/publications/projects-selected-for-the-regulators-pioneer-fund/projects-selected-for-the-regulators-pioneer-fund-2022" target="_blank" rel="noopener noreferrer">Pioneer Fund-backed project</a>, the frequency of regulatory overlap will be supported by metadata standardisation. </p>' +
      '<p>In the coming months the BRE will use the insights and energy generated at the event on this topic to work together with regulators and government to move regulatory document metadata standardisation forward to support the data ecosystem. For this to be successful it is important that we collaborate, so if you want to contribute to this effort then please get in touch! </p>' +
      '<h4 class="govuk-heading-s">The role of Reg Tech</h4>' +
      '<p>Apart from optimising the work of regulators, one of the other key benefits of the ORP is how it can support the Reg Tech ecosystem in a variety of sectors. We explored this, with a really useful exchange between regulators and RegTech providers. It became clear there’s a need to think pro-actively about how regulators can support Reg Tech, and the different roles each has to play to support people and businesses in complying with regulation.</p>' +
      '<p>The benefits of this approach were discussed in detail by the FCA – one of the regulators at the forefront of efforts to encourage <a href="https://www.fca.org.uk/firms/innovation/regtech" target="_blank" rel="noopener noreferrer">Reg Tech innovation</a>. They noted the importance of remaining agnostic to the types of technology used or the providers who are offering it, but by considering how regulations can be made more usable by Reg Tech providers and executing on a process of engagement with the ecosystem, they have been able to support finance businesses to achieve compliance in smarter ways. </p>' +
      '<p>There was also reflection from attendees on how Reg Tech tools used by regulated businesses could include regulatory compliance as part of their service offering. As the ORP moves into the next stage of its roadmap, this is a topic that regulators, Reg Tech providers and various stakeholders will be able to explore in greater depth. The BRE will be supporting creative and efficient approaches to how technology can be better leveraged in the economy to encourage compliance and innovation while supporting growth.</p>' +
      '<h4 class="govuk-heading-s">The processes required to embed regulatory innovation </h4>' +
      '<p>Regulators having the ambition to innovate within their organisation and to promote it externally is the first step, but we heard during the discussion at the event about the value of processes and tools when delivering on this ambition. The National Highways joined our panel discussion to shed light on the development of their <a href="https://www.standardsforhighways.co.uk/" target="_blank" rel="noopener noreferrer">Standards for Highways</a> project. Through creating a new tool which is used to write the guidance and standards that the National Highways issue, they have been able to transform how users of that information can interact with it, improve organisational efficiency and innovation. </p>' +
      '<h3 class="govuk-heading-m">The role of the ORP </h3>' +
      '<p>While the Open Regulation Platform continues to develop, the Better Regulation Executive will leverage the insights gathered as well as the connections established with regulators and other stakeholder who want to enhance innovation. Data standards will form a crucial element of the next phases of work and the insights of those that will benefit from it will be central to the standardisation process. The ORP will also help shape how Reg Tech providers can develop new tools or enhance their current solutions by making regulatory material machine-readable and accessible in a single dataset for the first time. The BRE will also consider how additional tooling can be developed to ensure the process of embedding innovation can be made more easily by regulators. </p>' +
      '<p>To find out more about any of these learnings, or to find out how you can be part of the next stages of the ORP’s development, get in touch with the BRE team! </p>' +
      '</ol>',
  },
};

export default BlogPosts;
