const BlogPosts = {
  1: {
    id: 1,
    title: 'Making regulation more accessible: Value driven by the ORP',
    author: 'Better Regulation Executive',
    date: '8 March 2023',
    tags: [{ name: 'Content tag', href: '#' }],
    description:
      'The Open Regulation Platform (ORP) has a simple objective: to create a platform which provides UK regulation as enriched, machine-readable data. By meeting this objective, the ORP will be an enabling service that can support the development of a range of tools that ensure regulation in the UK is digital-first and accessible to business in smarter ways.',
    // youtubeId: 'X2juNBpHtaU',
    image: {
      name: 'laptop.jpg',
      alt: 'man looking at an ipad',
    },
    content:
      '<p>The Open Regulation Platform (ORP) has a simple objective: to create a platform which provides UK regulation as enriched, machine-readable data. By meeting this objective, the ORP will be an enabling service that can support the development of a range of tools that ensure regulation in the UK is digital-first and accessible to business in smarter ways.</p>' +
      '<p><a href="https://www.gov.uk/government/publications/build-back-better-our-plan-for-growth/build-back-better-our-plan-for-growth-html" target="_blank" rel="noopener noreferrer">Less than a third</a> of UK businesses believe that the UK Government’s approach to regulation supports them in bringing new products and services to market. For the UK to have a regulatory system that is pro-innovation and provides a supportive environment to dynamic entrepreneurial business across all industries, regulatory reform needs to encourage new processes, products and business models.</p>' +
      '<p>The Open Regulation Platform helps to achieve several goals in the Innovation pillar from the Treasury’s Build Back Better: Plan for Growth report and the project is directly highlighted in the section on developing a regulatory system for an innovative economy. The strategy commits to “[harnessing] technology to ease the burdens of engaging with regulation” by “[converting] UK business legislation into machine-readable data to drive the development of RegTech apps.”</p>' +
      '<p>The ORP will ensure that there is co-ordinated digitisation and standardisation of information produced by regulators. This is something that will only become more important over time as new or adapted regulations are added to a growing corpus. The ORP will support efforts made by the UK Government and regulators – individually and collectively – to progress work that makes regulation easier to understand and access. </p>' +
      '<p>The need for accessible and easily understood regulation has been highlighted in the last few years. The response to the COVID-19 pandemic demonstrated how quickly regulations can change or be introduced. The UK’s departure from the European Union has also required an ongoing response from regulators which impacts UK businesses. <a href="https://www.gov.uk/government/news/the-retained-eu-law-revocation-and-reform-bill-2022#:~:text=Retained%20EU%20Law%20is%20a,on%20the%20statute%20book%20indefinitely." target="_blank" rel="noopener noreferrer">The Retained EU Law Bill</a> that is currently progressing through Parliament seeks to enable retained EU rules to be modified, updated or removed so that they are well-suited for the UK. As UK regulation changes due to the powers proposed in the Bill the demand for regulatory guidance and information that is easy to find and understand is likely to be enhanced. </p>' +
      '<p>In addition to Government or regulator led projects that seek to improve the accessibility of regulatory guidance, the ORP also supports private sector innovators and entrepreneurs. Tools – known as Reg Tech – that help businesses to understand their regulatory obligations across the broad range of regulations that they often need to comply with. They can also be part of the process that allows businesses to demonstrate their compliance. Reg Tech providers can leverage the ORP as part of their product development.</p>' +
      '<p>Currently, <a href="https://app.dev.cannonband.com/about#:~:text=BEIS%E2%80%99s%20Business%20Perception%20Survey%20from%202020" target="_blank" rel="noopener noreferrer">around eight staff days</a> per month are spent on average by UK business complying with regulation. Reg Tech tools can support greater efficiency in achieving regulatory compliance, freeing time and resource for business to allocate to revenue-generating or cost-saving activities.  </p>' +
      '<p>As well as supporting businesses grow by reducing their regulatory burden, dynamic and competitive Reg Tech markets can contribute to the UK economy on their own accord. In the finance industry the Financial Conduct Authority has embraced the approach the ORP now seeks to take by making their guidance and other regulatory material digitally accessible and standardised through their digital handbook. The <a href="https://www.gov.uk/government/publications/the-kalifa-review-of-uk-fintech" target="_blank" rel="noopener noreferrer">Kalifa Report</a>, which reviewed Reg Tech tools in the financial industry (Fin Tech), highlighted the importance of the FCA’s overall approach in supporting the UK’s Fin Tech sector which generated £11bn of revenue in 2021.  </p>' +
      '<p>The ORP has been designed to help current or future Reg Tech providers across a broad range of industries to access the dataset of regulatory material they can build from. The platform has a series of API endpoints that can be used alongside a web portal that can be used for online searching of regulatory material to access regulatory material easily and automatically.</p>' +
      '<p>The Better Regulation Executive within the Department for Business and Trade is uniquely placed to co-ordinate this work. The BRE’s existing relationships with regulators across the public sector and knowledge of the Reg Tech sector has ensured that development of the ORP has placed the needs and experiences of regulators and Reg Tech providers at the centre of the project. Our next blog post will reflect on the design and development approach we have employed, and will share the key user research insights.</p>' +
      '<p>We will continue to take a user-centred approach to developing the ORP, through user testing and frequent engagement with regulators and Reg Tech creators. We will also coordinate with other efforts to organise regulation standards such as the <a href="https://www.gov.uk/government/publications/better-regulation-framework" target="_blank" rel="noopener noreferrer">Better Regulation Framework</a>. Over the coming months and years, the ORP will support the Government, regulators and Reg Tech providers to transform how UK businesses find, understand and comply with regulatory guidance and legislation. </p>',
  },
};

export default BlogPosts;
