const pageTitles = {
  '/': 'The Open Regulation Platform blog',
  '/blog': 'The Open Regulation Platform blog',
  '/about': 'About the Open Regulation Platform',
  '/subscribe': 'Subscribe and manage your subscription',
  '/subscribe/manage': 'Manage your subscription',
  '/search': 'Search for regulatory material',
  '/unauthorised/ingest': 'Unauthorised: Upload documents',
  '/unauthorised/developer': 'Unauthorised: Developer portal',
  '/auth/login': 'Sign in',
  '/auth/register': 'Create an account',
  '/auth/unconfirmed': 'Email address unconfirmed',
  '/auth/resent-confirmation': 'Resend confirmation link',
  '/auth/delete-user': 'Delete your account',
  '/auth/delete-user-confirmation': 'Delete account confirmation',
  '/auth/email-sent': 'Email sent confirmation',
  '/auth/access-code': 'Access code submission',
  '/auth/limit-exceeded': 'Login attempt limit exceeded',
  '/ingest': 'Upload a document',
  '/ingest/upload': 'Choose a document',
  '/ingest/document-type': 'Choose a document type',
  '/ingest/document-topics': 'Choose document topics',
  '/ingest/document-status': 'Choose document status',
  '/ingest/submit': 'Review document details',
  '/ingest/success': 'Document upload success',
  '/developer': 'Your API credentials',
  '/developer/metadata-schema': 'Metadata Schema',
  '/cookies': 'Cookies',
  '/sitemap': 'Sitemap',
  '/accessibility': 'Accessibility statement',
  '/privacy': 'Privacy',
  '/uploaded-documents': 'Uploaded documents',
};

export default pageTitles;
