name: Create Release

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed
    tags:
      - 'v*'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Create new Release on GitHub
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
<<<<<<< Updated upstream
          tag_name: ${{ github.job }}
          release_name: ${{ github.job }}
=======
          tag_name: ${{ github.run_number }}.${{ github.run_attempt }}
          release_name: ${{ github.run_number }}.${{ github.run_attempt }}
>>>>>>> Stashed changes
          draft: false
          prerelease: false
